include:
  - project: 'qqvp/cmake-boilerplate'
    file: 'gitlab-ci-template.yml'

.build_job_template:
  extends:
    - .clone_firmware_images_repo
    - .general_build_job_template
  variables:
    REPO_CMAKE_ARGS: -DQQVP_RESULTS_DIR=${RESULTS_DIR} # From cmake-boilerplate
    FIRMWARE_REPO_VAR_NAME: QQVP_FIRMWARE_REPO_DIR
    FIRMWARE_REPO_SHA_FILE: ./tests/quic-vp/firmware-repo-sha.txt

lua-check:
  extends: .mr-job
  stage: test
  script: ./scripts/luacheckpatch.py $TARGET_REF $SOURCE_REF
  allow_failure: true
